spring.application.name=GestionProjet
spring.datasource.url=jdbc:mysql://localhost:3306/gestionprojet?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8088
# ==================== JWT Configuration ====================
jwt.secret=MaSuperSecretKeyPourJWT2026TresLongueEtSecuriseeAuMoins256BitsPourHS512
jwt.expiration=86400000
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sarramadeh@gmail.com
spring.mail.password=zuaq hune pgdd siol
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=sarramadeh@gmail.com
app.security.reset-code-expiration-minutes=10
