spring.application.name=GestionProjet
spring.datasource.url=jdbc:mysql://localhost:3306/gestionprojet?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.port=8088
# ==================== JWT Configuration ====================
jwt.secret=MaSuperSecretKeyPourJWT2026TresLongueEtSecuriseeAuMoins256BitsPourHS512
jwt.expiration=86400000